//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artículo
    {
        public Artículo()
        {
            this.Artículos_Características = new HashSet<Artículos_Características>();
            this.ComprasDetalles = new HashSet<ComprasDetalle>();
            this.EmpeñosDetalle = new HashSet<EmpeñoDetalle>();
            this.VentasDetalles = new HashSet<VentasDetalle>();
        }
    
        public string Código { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Código_Categoría { get; set; }
        public decimal Valor { get; set; }
        public byte Estado { get; set; }
        public string Notas { get; set; }
        public byte[] Foto { get; set; }
    
        public virtual Categoría Categorías { get; set; }
        public virtual ICollection<Artículos_Características> Artículos_Características { get; set; }
        public virtual ICollection<ComprasDetalle> ComprasDetalles { get; set; }
        public virtual ICollection<EmpeñoDetalle> EmpeñosDetalle { get; set; }
        public virtual ICollection<VentasDetalle> VentasDetalles { get; set; }
    }
}
