//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Características
    {
        public Características()
        {
            this.Artículos_Características = new HashSet<Artículos_Características>();
            this.Categorías = new HashSet<Categoría>();
        }
    
        public int Código { get; set; }
        public string Nombre { get; set; }
        public string TipoDeDato { get; set; }
    
        public virtual ICollection<Artículos_Características> Artículos_Características { get; set; }
        public virtual ICollection<Categoría> Categorías { get; set; }
    }
}
