//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Categoría
    {
        public Categoría()
        {
            this.Artículos = new HashSet<Artículo>();
            this.Características = new HashSet<Características>();
        }
    
        public int Código { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Artículo> Artículos { get; set; }
        public virtual ICollection<Características> Características { get; set; }
    }
}
