//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Compras = new HashSet<Compra>();
            this.Empeños = new HashSet<Empeño>();
            this.Ventas = new HashSet<Venta>();
        }
    
        public string Código { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string NombreCompleto { get; set; }
        public string Género { get; set; }
        public string Teléfono { get; set; }
        public string Email { get; set; }
        public bool RecibirNotificaciones { get; set; }
        public string Dirección { get; set; }
        public string Notas { get; set; }
        public string Foto { get; set; }
    
        public virtual ICollection<Compra> Compras { get; set; }
        public virtual ICollection<Empeño> Empeños { get; set; }
        public virtual ICollection<Venta> Ventas { get; set; }
    }
}
