//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Compra
    {
        public int Código { get; set; }
        public string Código_Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte Estado { get; set; }
        public string Notas { get; set; }
    
        public virtual Cliente Cliente { get; set; }
    }
}
