//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EmpeñosEntities : DbContext
    {
        public EmpeñosEntities()
            : base("name=EmpeñosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Artículo> Artículos { get; set; }
        public DbSet<Artículos_Características> Artículos_Características { get; set; }
        public DbSet<Características> Características { get; set; }
        public DbSet<Categoría> Categorías { get; set; }
        public DbSet<Cliente> Clientes { get; set; }
        public DbSet<Compra> Compras { get; set; }
        public DbSet<ComprasDetalle> ComprasDetalles { get; set; }
        public DbSet<Empeño> Empeños { get; set; }
        public DbSet<EmpeñoDetalle> EmpeñoDetalles { get; set; }
        public DbSet<EmpeñoGarantía> EmpeñoGarantías { get; set; }
        public DbSet<EmpeñoPago> EmpeñoPagos { get; set; }
        public DbSet<Parámetros> Parámetros { get; set; }
        public DbSet<Venta> Ventas { get; set; }
        public DbSet<VentasAbono> VentasAbonos { get; set; }
        public DbSet<VentasDetalle> VentasDetalles { get; set; }
    }
}
