//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpeñoPago
    {
        public int Código_Empeño { get; set; }
        public int Cuota { get; set; }
        public System.DateTime Fecha { get; set; }
        public decimal Intereses { get; set; }
        public decimal Abono { get; set; }
    
        public virtual Empeño Empeños { get; set; }
    }
}
