//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parámetros
    {
        public int Id { get; set; }
        public int PeriodoDeCobro { get; set; }
        public int Plazo { get; set; }
        public decimal PorcentajePréstamo { get; set; }
        public decimal PorcentajeInterés { get; set; }
    }
}
