//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empeños.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Venta
    {
        public Venta()
        {
            this.ComprasDetalles = new HashSet<ComprasDetalle>();
            this.VentasDetalles = new HashSet<VentasDetalle>();
        }
    
        public int Código { get; set; }
        public string Código_Cliente { get; set; }
        public System.DateTime Fecha { get; set; }
        public byte Estado { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual ICollection<ComprasDetalle> ComprasDetalles { get; set; }
        public virtual VentasAbono VentasAbono { get; set; }
        public virtual ICollection<VentasDetalle> VentasDetalles { get; set; }
    }
}
